"""
Centralized Prompt Management System
"""

from .agent_prompts import (
    ASSESSMENT_SYSTEM,
    CITY_COUNTRY_INFERENCE,
    DAYS_RECOMMENDATION,
    MEMORY_SUMMARY,
    ITINERARY_GENERATION_SYSTEM,
    ITINERARY_GENERATION_USER,
    RISK_ASSESSMENT,
    SEASONAL_NOTE,
    format_prompt
)

__all__ = [
    'ASSESSMENT_SYSTEM',
    'CITY_COUNTRY_INFERENCE',
    'DAYS_RECOMMENDATION',
    'MEMORY_SUMMARY',
    'ITINERARY_GENERATION_SYSTEM',
    'ITINERARY_GENERATION_USER',
    'RISK_ASSESSMENT',
    'SEASONAL_NOTE',
    'format_prompt'
]
